#Numpy (Numerical Python) is powerful python library. used for numerical computing.

It support larde multi dimensional arrays and matrices. along with a collection of mathematical function.

In [1]:
!pip install numpy

In [2]:
import numpy

In [4]:
import numpy as np
#as - alias   - short name

#Array - arrangement of elements in the form of dimensions

1D - 1 dimension

2D - 2 dimension

3D - 3 dimension

In [5]:
arr = np.array([1,2,3,4,5,6,7,8])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr1= np.array([[1,2,3], [4,5,6]])

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

#array attributes

In [ ]:
#.ndim - number of dimension

In [9]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
#.shape (rows, columns)

In [13]:
arr.shape

(8,)

In [14]:
arr1.shape

(2, 3)

In [15]:
#size - total no. of element

In [16]:
arr.size

8

In [17]:
arr1.size

6

In [ ]:
##dtype - data atype

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr1.dtype

dtype('int64')

#matrix

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.full((3,3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

indexing and slicing

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr[4]   #indexing- accessing one element only

5

In [28]:
arr[0:4]  #slicing- accessing range of elements

array([1, 2, 3, 4])

In [29]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2[1,2]

6

In [34]:
arr2[0:2, 1:3]   #0:2 - 0 & 1st rows // 1:3 1st and 2nd column

array([[2, 3],
       [5, 6]])

In [33]:
arr2[2,0]

7

#reshaping and flatten

In [35]:
arr = np.array([1,2,3,4,5,6])

In [37]:
arr.size

6

In [38]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [41]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [43]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr2.size

9

In [46]:
arr2.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
arr2.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
arr3= np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [49]:
arr3.size

12

In [50]:
arr3.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr3.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
arr3.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [54]:
arr3.ndim

1

In [56]:
arr4 = arr3.reshape(1,12)

In [57]:
arr4.ndim

2

In [58]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
arr4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])