In [1]:
import numpy as np

In [2]:
np.arange(5)  #array of range

array([0, 1, 2, 3, 4])

In [3]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [4]:
np.arange(2,9,2)  # 2,9 is range, last 2 is stepsize

array([2, 4, 6, 8])

In [9]:
np.linspace(0,10,50 )

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
arr = np.array([8,4,5,7,9,6,2,1,4,5,3])

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9])

In [12]:
arr.max()

9

In [13]:
arr.min()

1

In [14]:
arr.sum()

54

In [15]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr

array([8, 4, 5, 7, 9, 6, 2, 1, 4, 5, 3])

In [17]:
np.mean(arr)

4.909090909090909

In [18]:
np.median(arr)

5.0

In [20]:
from scipy import stats

In [21]:
stats.mode(arr)

ModeResult(mode=4, count=2)

In [22]:
arr

array([8, 4, 5, 7, 9, 6, 2, 1, 4, 5, 3])

In [23]:
np.var(arr)

5.537190082644629

In [24]:
np.std(arr)

2.3531234737354154

In [25]:
np.corrcoef(arr)

1.0

In [26]:
np.percentile(arr, 25)

3.5

In [27]:
np.percentile(arr,50)

5.0

In [28]:
np.percentile(arr,75)

6.5

In [29]:
np.percentile(arr, 75) - np.percentile(arr, 25)

3.0

In [30]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

In [31]:
np.corrcoef(x,y)

array([[1., 1.],
       [1., 1.]])

In [32]:
np.cov(x,y)

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

In [34]:
np.random.randint(1,100,5)

array([23, 60, 86, 54, 46])

In [38]:
np.random.rand(5)  #by default range is 0 to 1

array([0.84587863, 0.94483093, 0.81156194, 0.1790572 , 0.5598978 ])

In [39]:
np.random.randn(5)  #randn- normal distribution , mean = 0, std = 1

array([-0.77656563,  0.0537862 , -0.75443467, -0.35904071, -1.83745218])